"""Attach PyPI release hashes to an exact pip freeze snapshot (Python 3.13).

Usage: python scripts/hash_lock.py requirements.lock
Run only after resolving and testing a dependency update in a clean environment.
"""

import concurrent.futures
import json
import re
import sys
from pathlib import Path
from urllib.request import urlopen


def release_hashes(requirement):
    name, version = requirement.split("==")
    with urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as response:
        data = json.load(response)
    hashes = sorted({file["digests"]["sha256"] for file in data["urls"] if not file.get("yanked")})
    if not hashes:
        raise ValueError(f"No non-yanked distributions available for {requirement}")
    return requirement + " \\\n" + " \\\n".join("    --hash=sha256:" + digest for digest in hashes)


def main():
    path = Path(sys.argv[1])
    requirements = [
        line.rstrip(" \\")
        for line in path.read_text().splitlines()
        if re.fullmatch(r"[A-Za-z0-9_.-]+==[A-Za-z0-9_.!+-]+(?: \\)?", line)
    ]
    if not requirements:
        raise ValueError("Expected an exact-version pip freeze snapshot.")
    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        lines = list(pool.map(release_hashes, requirements))
    path.write_text(
        "# Python 3.13 runtime dependency snapshot, with PyPI distribution hashes.\n"
        "# Generated by scripts/hash_lock.py; upgrade in a clean environment and test.\n"
        + "\n".join(lines)
        + "\n"
    )


if __name__ == "__main__":
    main()
